dvrk:
  SUJ:
    SUJ_PSM1_J0_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM1_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM1_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM1_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM1_J4_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_ECM_J0_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_ECM_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_ECM_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_ECM_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J0_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J4_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J0_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J4_controller:
      p: 2000
      i: 0
      d: 10
  PSM1:
    yaw_joint_controller:
      p: 500
      i: 0.1
      d: 10
    pitch_back_joint_controller:
      p: 800
      i: 0.1
      d: 30
    main_insertion_joint_controller:
      p: 600
      i: 0.01
      d: 10
    large_needle_driver:
      tool_roll_joint_controller:
        p: 100
        i: 0.1
        d: 10
      tool_pitch_joint_controller:
        p: 100
        i: 0.1
        d: 10
      tool_yaw_joint_controller:
        p: 100
        i: 0.1
        d: 10
      gripper1_joint_controller:
        p: 100
        i: 0.1
        d: 10
      gripper2_joint_controller:
        p: 100
        i: 0.1
        d: 10
  PSM2:
    yaw_joint_controller:
      p: 500
      i: 0.1
      d: 10
    pitch_back_joint_controller:
      p: 800
      i: 0.1
      d: 30
    main_insertion_joint_controller:
      p: 600
      i: 0.01
      d: 10
    large_needle_driver:
      tool_roll_joint_controller:
        p: 100
        i: 0.1
        d: 10
      tool_pitch_joint_controller:
        p: 100
        i: 0.1
        d: 10
      tool_yaw_joint_controller:
        p: 100
        i: 0.1
        d: 10
      gripper1_joint_controller:
        p: 100
        i: 0.1
        d: 10
      gripper2_joint_controller:
        p: 100
        i: 0.1
        d: 10
  PSM3:
    yaw_joint_controller:
      p: 500
      i: 0.1
      d: 10
    pitch_back_joint_controller:
      p: 800
      i: 0.1
      d: 30
    main_insertion_joint_controller:
      p: 600
      i: 0.01
      d: 10
    large_needle_driver:
      tool_roll_joint_controller:
        p: 100
        i: 0.1
        d: 10
      tool_pitch_joint_controller:
        p: 100
        i: 0.1
        d: 10
      tool_yaw_joint_controller:
        p: 100
        i: 0.1
        d: 10
      gripper1_joint_controller:
        p: 100
        i: 0.1
        d: 10
      gripper2_joint_controller:
        p: 100
        i: 0.1
        d: 10
  ecm:
    yaw_joint_controller:
      p: 700
      i: 1
      d: 90
    pitch_front_joint_controller:
      p: 700
      i: 1
      d: 50
    main_insertion_joint_controller:
      p: 500
      i: 0.1
      d: 20
    tool_joint_controller:
      p: 200
      i: 0.1
      d: 10
