transmission_description:
  transimssion_1:
    type: transmission_interface/SimpleTransmission
    joint:
      name: dvrk/ecm/yaw_joint
      hardware_interface: hardware_interface/EffortJointInterface
    actuator:
      name: a1
      mechanical_reduction: 1

  transmission_2:
    type: transmission_interface/SimpleTransmission
    joint:
      name: dvrk/ecm/pitch_front_joint
      hardware_interface: hardware_interface/EffortJointInterface
    actuator:
      name: a2
      mechanical_reduction: 1
